Portal/Models/CreatePackageViewModel.cs
using Core.Domain;
using Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Portal.Models
{
    public class CreatePackageViewModel
    {
        public string? Name { get; set; }
        public int Price { get; set; }
        public City City { get; set; }
        public Meal Meal { get; set; }
        public DateTime RetrieveDate { get; set; }
        public DateTime DeadLineRetriveDate { get; set; }

        //public List<Product> Products { get; } = [];

        public List<int> SelectedProductIds { get; set; }

        public MultiSelectList Products { get; set; }
    }
}

Portal/Models/PackageDetailsViewModel.cs
using Core.Domain;
using Infrastructure;

namespace Portal.Models
{
    public class PackageDetailsViewModel
    {
        public Package? Package { get; set; }

        public List<Product> Products { get; set; }
    }
}

Portal/Models/PackageViewModel.cs
using Core.Domain;
using Infrastructure;

namespace Portal.Models
{
    public class PackageViewModel
    {
        public IEnumerable<Package> Packages { get; set; } = Enumerable.Empty<Package>();
        public string ErrorMessage { get; set; }
        public IEnumerable<Canteen> Canteens { get; set; } = Enumerable.Empty<Canteen>();

        public Employee? Employee { get; set; }
    }
}

Portal/Controllers/PackageController.cs
using Core.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portal.Models;
using System.Security.Claims;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Infrastructure.EP_EF.Repositories;

namespace Portal.Controllers
{
    public class PackageController : Controller
    {

        private readonly IPackageRepository _packageRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ICanteenRepository _canteenRepository;
        private readonly IProductRepository _productRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly UserManager<IdentityUser> _userManager;


        public PackageController(IPackageRepository packageRepository, IStudentRepository studentRepository
            , UserManager<IdentityUser> userManager, ICanteenRepository canteenRepository, IProductRepository productRepository, IEmployeeRepository employeeRepository)
        {
            _packageRepository = packageRepository;
            _studentRepository = studentRepository;
            _userManager = userManager;
            _canteenRepository = canteenRepository;
            _productRepository = productRepository;
            _employeeRepository = employeeRepository;
        }

        public async Task<IActionResult> PackageList()
        {

            var viewModel = new PackageViewModel
            {
                Packages = _packageRepository.GetNonReservePackage(),
                Canteens = _canteenRepository.GetAll(),
            };
            if (User.HasClaim("Employee", "true")){
                var user = User.FindFirst(ClaimTypes.Name);
               // var employee = await _employeeRepository.GetEmployeeByEmployeeNumber(int.Parse(user.Value));
               viewModel.Employee = await _employeeRepository.GetEmployeeByEmployeeNumber(int.Parse(user.Value));
            }
           
            viewModel.ErrorMessage = TempData["ErrorMessage"] as string;
            TempData.Clear();
            return View("PackageList", viewModel);
        }
        public IActionResult CanteenList(int canteenId)
        {
            
            var viewModel = new PackageViewModel
            {
                Packages = _packageRepository.GetNonReservePackage()
                .Where(r => r.CanteenId == canteenId)
                .OrderBy(r => r.RetrieveDate).ToList(),

                Canteens = _canteenRepository.GetAll(),
                //Packages = _packageRepository.GetReservedPackagesByLocation(canteenId),
            };
            viewModel.ErrorMessage = TempData["ErrorMessage"] as string;
            TempData.Clear();
            return View("PackageList", viewModel);
        }

        /*
                [HttpPost]

                public async Task<IActionResult> ReservePackage(Package package,Student student)
                {

                   // var reservationStudent =  _packageRepository.ReservePackage(package, student);
                   await _packageRepository.ReservePackage(package, student);
                    System.Diagnostics.Debug.WriteLine(package.Id);
                    return Redirect("PackageList");

                }*/

        [HttpPost]
        [Authorize(Policy = "StudentPolicy")]
        public async Task<IActionResult> ReservationPackages(int packageId)
        {
            try
            {
                var user = User.FindFirst(ClaimTypes.Name);
                var student = await _studentRepository.GetStudentByStudentNumber(int.Parse(user.Value));
                var package = _packageRepository.GetPackageById(packageId);

                // package.ReservePackage = student;
            

                await _packageRepository.ReservePackage(package, student);
                
                // Save changes to the database asynchronously


                return RedirectToAction("ReservationPackages");
            }catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("PackageList");
            }
            
        }
        [Authorize(Policy = "StudentPolicy")]
        public IActionResult ReservationPackages()
        {
            
                var user = User.FindFirst(ClaimTypes.Name);

                var viewModel = new PackageViewModel
                {
                    Packages = _packageRepository.GetReservePackage().Where(r => r.reserverdByStudent.StudentNumber == int.Parse(user.Value))

                };
                return View("ReservationPackages", viewModel);

            
            
            
        }
        [HttpGet]
        [Authorize(Policy = "EmployeePolicy")]
        public IActionResult CreatePackage()
        {
            var user = User.FindFirst(ClaimTypes.Name);
            var allProducts = _productRepository.GetAll();

            var viewModel = new CreatePackageViewModel
            {
                Products = new MultiSelectList(allProducts, nameof(Product.Id), nameof(Product.Name))
            };

            return View(viewModel);
        }
        [HttpPost]
        [Authorize(Policy = "EmployeePolicy")]
        public async Task<IActionResult> CreatePackage(CreatePackageViewModel createPackageViewModel)
        {
            var user = User.FindFirst(ClaimTypes.Name);
            var employee =await _employeeRepository.GetEmployeeByEmployeeNumber(int.Parse(user.Value));

            var correspondingProducts = _productRepository.GetAll().Where(r=>createPackageViewModel.SelectedProductIds.Contains(r.Id));
            await _packageRepository.AddPackage(new Package
            {

                Name = createPackageViewModel.Name,
                Price = createPackageViewModel.Price,
                Canteen = employee.Canteen,
                Meal = createPackageViewModel.Meal,
                RetrieveDate = createPackageViewModel.RetrieveDate,
                DeadLineRetriveDate = createPackageViewModel.DeadLineRetriveDate,
                Products = correspondingProducts.ToList(),
            }) ;

            return RedirectToAction("Packagelist");
        }
        /*[HttpPost]
       public IActionResult PackageDetails(int packageId)
        {
            var package = _packageRepository.GetPackageById(packageId);

            var packageViewDetailsModel = new PackageDetailsViewModel
            {
                // Copy the existing packages
                Package = package,
                Products = package.Products
                // Assign the loaded products to the Products property
   
            };

            return View(packageViewDetailsModel);

        }*/
        public IActionResult PackageDetails(int packageId)
        {
            var package = _packageRepository.GetPackageById(packageId);

            var packageViewDetailsModel = new PackageDetailsViewModel
            {
                // Copy the existing packages
                Package = package,
                Products = package.Products
                // Assign the loaded products to the Products property

            };

            return View(packageViewDetailsModel);
        }

        [HttpPost]
        [Authorize(Policy = "EmployeePolicy")]
        public async Task<IActionResult> DeletePackage(int packageId)
        {
            var user = User.FindFirst(ClaimTypes.Name);
            var employee = await _employeeRepository.GetEmployeeByEmployeeNumber(int.Parse(user.Value));
            var package = _packageRepository.GetPackageById(packageId);

            await _packageRepository.RemovePackage(package);

            return RedirectToAction("Packagelist");

        }

        [HttpPost]
        [Authorize(Policy = "EmployeePolicy")]
        public async Task<IActionResult> UpdatePackage(CreatePackageViewModel updatePackageViewModel)
        {
            var user = User.FindFirst(ClaimTypes.Name);
            var employee = await _employeeRepository.GetEmployeeByEmployeeNumber(int.Parse(user.Value));

            var correspondingProducts = _productRepository.GetAll().Where(r => updatePackageViewModel.SelectedProductIds.Contains(r.Id));

            //var package = _packageRepository.GetPackageById(packageId);

        //    await _packageRepository.EditPackage(updatePackageViewModel);

            return RedirectToAction("Packagelist");
        }

        [HttpGet]
        [Authorize(Policy = "EmployeePolicy")]
        public IActionResult UpdatePackage()
        {
            var user = User.FindFirst(ClaimTypes.Name);
            var allProducts = _productRepository.GetAll();

            var viewModel = new CreatePackageViewModel
            {
                Products = new MultiSelectList(allProducts, nameof(Product.Id), nameof(Product.Name))
            };

            return View(viewModel);
        }



    }
}

Portal/Views/Package/CreatePackage.cshtml
@using Core.Domain;
@model Portal.Models.CreatePackageViewModel;

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
            <img src="~/images/NieuweLogoWithoutLetters.png" width="120" height="120" class="d-inline-block align-top rounded-circle" alt="">

        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="ReservationPackages">Gereserveerde Pakketten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="PackageList">Pakketten Lijst</a>
                </li>
               


                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="CreatePackage">Maak pakket aan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Log uit</a>
                </li>
            </ul>
        </div>
    </nav>
    <h1>Maak pakket aan</h1>

    <div>
        <div>
            Dit is de website van EcoPlates.<br />
            (To do: sell it better. Add pictures or something.)
        </div>
        <form asp-action="CreatePackage" method="post" class="m-2">
            <div asp-validation-summary="All"></div>
            <div>
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" />
            </div>
            <div>
                <label asp-for="Price">Prijs:</label>
                <input asp-for="Price" />
            </div>
           
            <div>
                <label asp-for="City">Stad:</label>
                <select asp-for="City" asp-items="Html.GetEnumSelectList<City>()">
                    <option value="">Kies een stad</option>
                </select>
            </div>
            <div>
                <label asp-for="Meal">Type maaltijd:</label>
                <select asp-for="Meal" asp-items="Html.GetEnumSelectList<Meal>()">
                    <option value="">Kies een type maaltijd</option>
                </select>
            </div>

            <div>
                <label asp-for="RetrieveDate">Ophaaldatum:</label>
                <input asp-for="RetrieveDate" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>
            <div>
                <label asp-for="DeadLineRetriveDate">Deadline ophaaldatum:</label>
                <input asp-for="DeadLineRetriveDate" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group">
                <label for="SelectedProductIds">Select Products:</label>
                @Html.DropDownListFor(model => model.SelectedProductIds, Model.Products, new { @class = "form-control", multiple = "multiple" })
            </div>
            <button type="submit" class="btn btn-primary mt-3">Pakket plaatsten</button>
        </form>
    </div>

</body>
</html>

Portal/Views/Package/PackageDetails.cshtml
@model Portal.Models.PackageDetailsViewModel
@{
    Layout = null;
}

<html>
<body>
    <h2>Package Details</h2>

    <p>Package ID: @Model.Package.Id</p>
    <!-- Display other package details -->

    <h3>Products in Package:</h3>
    <div>
        @foreach (var product in Model.Products)
        {
            <p>@product.Name</p>
            <img src="@product.PhotoPath" width="120" height="120" />
            if(@product.ContainsAlcohol== true)
            {
                <p>dit product bevat alcohol</p>
            }
            
        }
    </div>
</body>
</html>

Portal/Views/Package/PackageList.cshtml
@model Portal.Models.PackageViewModel;
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
            <img src="~/images/NieuweLogoWithoutLetters.png" width="120" height="120" class="d-inline-block align-top rounded-circle" alt="">

        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="ReservationPackages">Gereserveerde Pakketten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="PackageList">Pakketten Lijst</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Kantine's
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                       
                        @foreach (var canteen in Model.Canteens)
                        {
                            <a class="dropdown-item" asp-controller="Package" asp-action="CanteenList" asp-route-canteenId="@canteen.Id">@canteen.LocationName</a>

                        }
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="CreatePackage">Maak pakket aan</a>
                </li>
                <li class="nav-item ms-auto">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Log uit</a>
                </li>
            </ul>
        </div>
    </nav>
      <h1>Pakketten</h1>
    <style>
        .align-right {
            text-align: right !important;
        }
    </style>
    
    @foreach (var package in Model.Packages)
    {

        <div class="card mb-3" style="max-width: 90rem;">
            <img class="card-img-top cropped-image" src="../images/packageImage.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@package.Name</h5>
            <p class="card-text">prijs: €@package.Price</p>
                <p class="card-text">locatie: @package.City, @package.Canteen.LocationName</p>
                <p class="card-text">Meal: @package.Meal</p>

                <form asp-controller="package" asp-action="packageDetails" method="post" class="m-2">
                    <input type="hidden" name="packageId" value="@package.Id" />
                    <button type="submit" class="btn btn-primary mt-3">Producten</button>
                </form>>

                
                


                <form asp-controller="package" asp-action="reservationPackages" method="post" class="m-2">
                    <input type="hidden" name="packageId" value="@package.Id"/>
            
                    @foreach (var product in package.Products)
                    {

                        <!-- Add other product details as needed -->
                        @if (product.ContainsAlcohol == true)
                        {
                            <p style="position: absolute; bottom: 0; right:0; color: red; font-size: 24px; font-weight: bold;">18+</p>

                        }
                        
                        

                    }
                   
                    @if (User.HasClaim("Student", "true"))
                    {
                        <button type="submit" class="btn btn-primary mt-3">Reserveer</button>

                    }
           


                </form>
                <form asp-controller="package" asp-action="deletePackage" method="post" class="m-2">
                    <input type="hidden" name="packageId" value="@package.Id" />
                    @if (User.HasClaim("Employee", "true") && package.Canteen.Id == Model.Employee?.CanteenId)
                    {
                        <button type="submit" class="btn btn-primary mt-3">Verwijderen</button>

                    }

                </form>
                <form asp-controller="package" asp-action="updatePackage" method="post" class="m-2">
                    <input type="hidden" name="packageId" value="@package.Id" />
                    @if (User.HasClaim("Employee", "true") && package.Canteen.Id == Model.Employee?.CanteenId)
                    {
                        <button type="submit" class="btn btn-primary mt-3">Wijzigen</button>

                    }

                </form>

                <p class="align-right">datum ophalen: @package.RetrieveDate</p>
        </div>
        

    </div>
        
    }
    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert alert-danger">
            @Model.ErrorMessage
        </div>
    }
   

    
</body>
</html>
  

Portal/Views/Package/ReservationPackages.cshtml
@model Portal.Models.PackageViewModel;
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/images/EcoPlatesIcon.png"/>
</head>
<body>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
            <img src="~/images/NieuweLogoWithoutLetters.png" width="120" height="120" class="d-inline-block align-top rounded-circle" alt="">

        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="ReservationPackages">Gereserveerde Pakketten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="PackageList">Pakketten Lijst</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Kantine's
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">

                        @foreach (var canteen in Model.Canteens)
                        {
                            <a class="dropdown-item" asp-controller="Package" asp-action="CanteenList" asp-route-canteenId="@canteen.Id">@canteen.LocationName</a>

                        }
                    </ul>
                </li>


                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="CreatePackage">Maak pakket aan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Log uit</a>
                </li>
            </ul>
        </div>
    </nav>
    <h1>Pakketten</h1>
    <style>
        .align-right {
            text-align: right !important;
        }
    </style>

    @foreach (var package in Model.Packages)
    {

        <div class="card mb-3" onclick="location.href='@Url.Action("reservePackage", "package",new { packageId = package.Id })';" style="cursor: pointer;">
            <img class="card-img-top cropped-image" src="../images/packageImage.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@package.Name</h5>
                <p class="card-text">prijs: €@package.Price</p>
                <p class="card-text">locatie: @package.City, @package.Canteen</p>
                <p class="card-text">Meal: @package.Meal</p>
            </div>
        </div>

    }


</body>
</html>

Portal/Views/Package/UpdatePackage.cshtml
@using Core.Domain;
@model Portal.Models.CreatePackageViewModel;

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
            <img src="~/images/NieuweLogoWithoutLetters.png" width="120" height="120" class="d-inline-block align-top rounded-circle" alt="">

        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="ReservationPackages">Gereserveerde Pakketten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="PackageList">Pakketten Lijst</a>
                </li>



                <li class="nav-item">
                    <a class="nav-link" asp-controller="Package" asp-action="CreatePackage">Maak pakket aan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Log uit</a>
                </li>
            </ul>
        </div>
    </nav>
    <h1>Wijzig pakket</h1>

    <div>
        <div>
            Dit is de website van EcoPlates.<br />
            (To do: sell it better. Add pictures or something.)
        </div>
        <form asp-action="CreatePackage" method="post" class="m-2">
            <div asp-validation-summary="All"></div>
            <div>
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" />
            </div>
            <div>
                <label asp-for="Price">Prijs:</label>
                <input asp-for="Price" />
            </div>

            <div>
                <label asp-for="City">Stad:</label>
                <select asp-for="City" asp-items="Html.GetEnumSelectList<City>()">
                    <option value="">Kies een stad</option>
                </select>
            </div>
            <div>
                <label asp-for="Meal">Type maaltijd:</label>
                <select asp-for="Meal" asp-items="Html.GetEnumSelectList<Meal>()">
                    <option value="">Kies een type maaltijd</option>
                </select>
            </div>

            <div>
                <label asp-for="RetrieveDate">Ophaaldatum:</label>
                <input asp-for="RetrieveDate" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>
            <div>
                <label asp-for="DeadLineRetriveDate">Deadline ophaaldatum:</label>
                <input asp-for="DeadLineRetriveDate" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group">
                <label for="SelectedProductIds">Select Products:</label>
                @Html.DropDownListFor(model => model.SelectedProductIds, Model.Products, new { @class = "form-control", multiple = "multiple" })
            </div>
            <button type="submit" class="btn btn-primary mt-3">Pakket plaatsten</button>
        </form>
    </div>

</body>
</html>